from django.urls import path
from .views import (
    DoctorList, DoctorCreate, DoctorProfileView,
    DoctorDegreeList, DoctorDegreeCreate, DoctorDegreeDeleteView,
    DoctorChangePassword, QuestionChoiceList, QuestionChoiceCreate,
    QuestionChoiceUpdate, QuestionChoiceDelete, QuestionList,
    QuestionCreate, QuestionUpdate, QuestionDelete,
    CounsellingQuestionSetList, CounsellingQuestionSetCreate,
    CounsellingQuestionSetUpdate, CounsellingQuestionSetDelete,
    PatientList, PatientCreate, PatientProfileView,
    PatientConsellingQuestionSets, PatientConsellingQuestionSetCreate,
    PatientConsellingQuestionForm, OrganizationList, OrganizationCreate,
    OrganizationUpdate, OrganizationDelete, DoctorVisitingSchedulesList,
    DoctorVisitingSchedulesCreate, DoctorVisitingSchedulesUpdate,
    DoctorVisitingSchedulesDelete, LabTestItemsList, LabTestItemsCreate,
    LabTestItemsUpdate, LabTestItemsDelete, LabTestsList, LabTestsCreate,
    LabTestsUpdate, LabTestsDelete, LabTestsItems, LabsList, LabsCreate,
    LabsUpdate, LabsDelete, LabsTests, LabAgentList, LabAgentsCreate,
    LabAgentsProfileUpdate
)

app_name = 'healthcare'

urlpatterns = [
    path('doctor/', DoctorList.as_view(), name="doctor_list"),
    path('doctor/create/', DoctorCreate.as_view(), name="doctor_add"),
    path('doctor/profile/<pk>', DoctorProfileView.as_view(), name="doctor_profile_update"),
    path('patient/', PatientList.as_view(), name="patient_list"),
    path('patient/create/', PatientCreate.as_view(), name="patient_add"),
    path('patient/profile/<pk>', PatientProfileView.as_view(), name="patient_profile_update"),
    path('doctor/degree/<pk>', DoctorDegreeList.as_view(), name="doctor_degree_list"),
    path('doctor/degree/<pk>/add', DoctorDegreeCreate.as_view(), name="doctor_degree_add"),
    path('doctor/degree/<pk>/delete', DoctorDegreeDeleteView.as_view(), name="doctor_degree_delete"),
    path('doctor/change-password/<pk>', DoctorChangePassword.as_view(), name="doctor_change_password"),
    path('questions-choices/', QuestionChoiceList.as_view(), name="question_choice"),
    path('questions-choices/create/', QuestionChoiceCreate.as_view(), name="question_choice_add"),
    path('questions-choices/update/<slug>', QuestionChoiceUpdate.as_view(), name="question_choice_update"),
    path('questions-choices/delete/<slug>', QuestionChoiceDelete.as_view(), name="question_choice_delete"),   
    path('questions/', QuestionList.as_view(), name='question_list'),
    path('questions/create/', QuestionCreate.as_view(), name="question_add"),
    path('questions/update/<pk>', QuestionUpdate.as_view(), name="question_update"),
    path('questions/delete/<pk>', QuestionDelete.as_view(), name="question_delete"),   
    path('counselling-question-set/', CounsellingQuestionSetList.as_view(), name='coun_question_set_list'),
    path('counselling-question-set/create/', CounsellingQuestionSetCreate.as_view(), name="coun_question_set_add"),
    path('counselling-question-set/update/<pk>', CounsellingQuestionSetUpdate.as_view(), name="coun_question_set_update"),
    path('counselling-question-set/delete/<pk>', CounsellingQuestionSetDelete.as_view(), name="coun_question_set_delete"),   
    path('counselling/patient/<pk>', PatientConsellingQuestionSets.as_view(), name="patient_counselling_question_sets_list"),   
    path('counselling/patient/create/<pk>', PatientConsellingQuestionSetCreate.as_view(), name="patient_counselling_question_sets_add"),   
    path('counselling/patient/create/form/<pk>', PatientConsellingQuestionForm.as_view(), name="patient_counselling_question_form"),   
    path('organizations/', OrganizationList.as_view(), name='organization_list'),
    path('organizations/create/', OrganizationCreate.as_view(), name='organization_add'),
    path('organizations/update/<slug>', OrganizationUpdate.as_view(), name='organization_update'),
    path('organizations/delete/<slug>', OrganizationDelete.as_view(), name='organization_delete'),
    path('doctor/visiting-hours/<pk>', DoctorVisitingSchedulesList.as_view(), name='doctor_schedule_list'),
    path('doctor/visiting-hours/<pk>/add', DoctorVisitingSchedulesCreate.as_view(), name='doctor_schedule_add'),  
    path('doctor/visiting-hours/<pk>/update', DoctorVisitingSchedulesUpdate.as_view(), name='doctor_schedule_update'),  
    path('doctor/visiting-hours/<pk>/delete', DoctorVisitingSchedulesDelete.as_view(), name='doctor_schedule_delete'),  
    path('lab-test-items/', LabTestItemsList.as_view(), name='lab_test_items_list'),
    path('lab-test-items/create/', LabTestItemsCreate.as_view(), name='lab_test_items_add'),
    path('lab-test-items/update/<pk>', LabTestItemsUpdate.as_view(), name='lab_test_items_update'),
    path('lab-test-items/delete/<pk>', LabTestItemsDelete.as_view(), name='lab_test_items_delete'),
    path('lab-tests/', LabTestsList.as_view(), name='lab_tests_list'),
    path('lab-tests/create/', LabTestsCreate.as_view(), name='lab_tests_add'),
    path('lab-tests/update/<slug>', LabTestsUpdate.as_view(), name='lab_tests_update'),
    path('lab-tests/delete/<slug>', LabTestsDelete.as_view(), name='lab_tests_delete'),
    path('lab-tests/items/<slug>', LabTestsItems.as_view(), name='lab_tests_items'),
    path('labs/', LabsList.as_view(), name='labs_list'),
    path('labs/create/', LabsCreate.as_view(), name='labs_add'),
    path('labs/update/<slug>', LabsUpdate.as_view(), name='labs_update'),
    path('labs/delete/<slug>', LabsDelete.as_view(), name='labs_delete'),
    path('labs/items/<slug>', LabsTests.as_view(), name='labs_tests'),
    path('labs/agents/<slug>', LabAgentList.as_view(), name="lab_agents"),
    path('labs/agents/<slug>/create', LabAgentsCreate.as_view(), name="lab_agents_add"),
    path('labs/agents/<pk>/update', LabAgentsProfileUpdate.as_view(), name="lab_agents_update"),
]
