# Generated by Django 2.2.4 on 2019-09-04 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20190904_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttransaction',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='warehouse.WareHouse'),
            preserve_default=False,
        ),
    ]
