# Generated by Django 2.2.4 on 2019-09-01 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import healthcare.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=healthcare.models.user_directory_path)),
                ('approval_status', models.CharField(choices=[('A', 'Approved'), ('U', 'Unapproved')], default='U', max_length=2, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Designation')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.SubDiscipline')),
                ('permanent_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Degree')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.DoctorProfile')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.University')),
            ],
            options={
                'unique_together': {('doctor', 'degree', 'university')},
            },
        ),
    ]
