# Generated by Django 2.2.4 on 2019-09-07 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import healthcare.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_agentprofile'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsellingQuestionSets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('D', 'Description'), ('O', 'Option')], max_length=1)),
                ('question_choices', models.ManyToManyField(to='healthcare.QuestionChoices')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=healthcare.models.user_directory_path)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Designation')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.SubDiscipline')),
                ('permanent_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientConsellingQuestionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding', models.TextField()),
                ('recommendation', models.TextField()),
                ('date', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healthcare.DoctorProfile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healthcare.PatientProfile')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healthcare.ConsellingQuestionSets')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('remark', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.Location')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorVistingSchedlues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healthcare.DoctorProfile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healthcare.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='ConsellingQuestionSetsAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healthcare.Question')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healthcare.PatientConsellingQuestionResult')),
            ],
        ),
        migrations.AddField(
            model_name='consellingquestionsets',
            name='question',
            field=models.ManyToManyField(to='healthcare.Question'),
        ),
    ]
