# Generated by Django 2.2.4 on 2019-09-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_auto_20190907_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsellingquestionresult',
            name='approval_status',
            field=models.CharField(choices=[('A', 'Approved'), ('U', 'Unapproved')], default='U', max_length=2),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='approval_status',
            field=models.CharField(choices=[('A', 'Approved'), ('U', 'Unapproved')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_choices',
            field=models.ManyToManyField(blank=True, to='healthcare.QuestionChoices'),
        ),
    ]
