# Generated by Django 2.2.4 on 2019-09-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_auto_20190908_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='discipline',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
