# Generated by Django 2.2.4 on 2019-09-08 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_auto_20190908_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='permanent_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
        ),
    ]
