# Generated by Django 2.2.4 on 2019-09-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0005_auto_20190908_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
