# Generated by Django 2.2.4 on 2019-09-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0007_auto_20190911_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientconsellingquestionresult',
            name='date',
        ),
        migrations.AddField(
            model_name='patientconsellingquestionresult',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientconsellingquestionresult',
            name='assigned_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
