# Generated by Django 2.2.4 on 2019-09-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0008_auto_20190911_1924'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientconsellingquestionresult',
            unique_together={('question_set', 'patient', 'assigned_date')},
        ),
    ]
