# Generated by Django 2.2.4 on 2019-09-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0012_auto_20190911_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientconsellingquestionresult',
            name='finding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
