# Generated by Django 2.2.4 on 2019-09-11 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0013_auto_20190911_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consellingquestionsetsanswers',
            name='answer_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthcare.QuestionChoices'),
        ),
        migrations.AlterField(
            model_name='consellingquestionsetsanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.Question'),
        ),
    ]
