# Generated by Django 2.2.4 on 2019-09-11 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthcare', '0014_auto_20190911_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
