# Generated by Django 2.2.4 on 2019-10-01 19:45

from django.db import migrations, models
import django.utils.timezone
import healthcare.models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0015_patientprofile_registered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
        migrations.AddField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=healthcare.models.organization_directory_path),
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
