# Generated by Django 2.2.4 on 2019-10-01 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0016_auto_20191001_1945'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorvistingschedlues',
            unique_together={('doctor', 'date', 'organization', 'in_time', 'out_time')},
        ),
    ]
