# Generated by Django 2.2.4 on 2019-10-01 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0017_auto_20191001_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorvistingschedlues',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
