# Generated by Django 2.2.4 on 2019-10-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0018_doctorvistingschedlues_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorVistingSchedlues',
            new_name='DoctorVistingSchedules',
        ),
    ]
