# Generated by Django 2.2.4 on 2019-10-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0020_labs_labtestitems_labtests'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtests',
            name='home_service',
            field=models.BooleanField(default=False),
        ),
    ]
