# Generated by Django 2.2.4 on 2019-10-14 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import healthcare.models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('core', '0006_useraccount_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthcare', '0021_labtests_home_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabAgentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField(null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=healthcare.models.user_directory_path)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2)),
                ('remark', models.TextField(blank=True, null=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Designation')),
                ('permanent_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labagent_registered_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
