# Generated by Django 2.2.4 on 2019-10-14 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0022_labagentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='labagentprofile',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='healthcare.Labs'),
            preserve_default=False,
        ),
    ]
