# Generated by Django 2.2.4 on 2019-10-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0024_patientconsellingquestionresult_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsellingquestionresult',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
