# Generated by Django 2.2.4 on 2019-10-19 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthcare', '0025_patientconsellingquestionresult_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientLabTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now=True)),
                ('address_detail', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('requested_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_code', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lab_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healthcare.LabAgentProfile')),
                ('labs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healthcare.Labs')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.Location')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healthcare.PatientProfile')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healthcare.LabTests')),
            ],
        ),
        migrations.CreateModel(
            name='PatientLabTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_results', models.CharField(max_length=255)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.PatientLabTest')),
                ('test_items', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healthcare.LabTestItems')),
            ],
        ),
    ]
