# Generated by Django 2.2.4 on 2019-10-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0026_patientlabtest_patientlabtestresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientlabtest',
            old_name='labs',
            new_name='lab',
        ),
    ]
