# Generated by Django 2.2.4 on 2019-10-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0027_auto_20191019_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlabtest',
            name='home_service',
            field=models.BooleanField(default=False),
        ),
    ]
