# Generated by Django 2.2.4 on 2019-10-20 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0028_patientlabtest_home_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlabtest',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.Location'),
        ),
    ]
