# Generated by Django 2.2.4 on 2019-11-02 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0030_auto_20191020_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientconsellingquestionresult',
            name='doctor',
        ),
        migrations.AddField(
            model_name='patientconsellingquestionresult',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='healthcare.DoctorVistingSchedules'),
        ),
    ]
