# Generated by Django 2.2.4 on 2019-09-01 19:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('user_type', models.CharField(choices=[('O', 'Online User'), ('S', 'Staff'), ('A', 'Agent'), ('D', 'Doctor'), ('P', 'Patient')], default='O', max_length=1)),
                ('account_status', models.CharField(choices=[('A', 'Active'), ('IA', 'In-Active')], default='A', max_length=2)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('IA', 'In-Active')], default='A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('IA', 'In-Active')], default='A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('IA', 'In-Active')], default='A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('IA', 'In-Active')], default='A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('website_link', models.CharField(max_length=255)),
                ('remark', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('IA', 'In-Active')], default='A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SubDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('IA', 'In-Active')], default='A', max_length=2)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('IA', 'In-Active')], default='A', max_length=2)),
                ('university', models.ManyToManyField(to='core.University')),
            ],
        ),
    ]
