# Generated by Django 2.2.4 on 2019-09-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agentprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentProfile',
        ),
    ]
