# Generated by Django 2.2.4 on 2019-10-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_agentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('O', 'Online User'), ('S', 'Staff'), ('A', 'Agent'), ('D', 'Doctor'), ('P', 'Patient'), ('L', 'Lab')], default='O', max_length=1),
        ),
    ]
