# Generated by Django 2.2.4 on 2019-10-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('core', '0005_auto_20191001_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='permissions',
            field=models.ManyToManyField(to='auth.Permission'),
        ),
    ]
