from django.urls import path
from .views import (
    LoginView, Dashboard, Logout,
    DisciplineList, DisciplineCreate, DisciplineUpdate,
    DisciplineDelete, SubDisciplineList, SubDisciplineCreate,
    SubDisciplineUpdate, SubDisciplineDelete, UniversityList,
    UniversityCreate, UniversityUpdate, UniversityDelete,
    DegreeList, DegreeCreate, DegreeUpdate, DegreeDelete,
    DesignationList, DesignationCreate, DesignationUpdate,
    DesignationDelete, get_university_via_degree, BrandList,
    BrandCreate, BrandUpdate, BrandDelete, ManufacturerList,
    ManufacturerCreate, ManufacturerUpdate, ManufacturerDelete,
    GroupList, GroupCreate, GroupUpdate, AgentList, AgentCreate,
    AgentProfileView, AgentChangePassword, AgentWarehouse,
    AgentWarehouseCreate
)


app_name = 'core'

urlpatterns = [
    path('login/', LoginView.as_view(), name='admin_login'),
    path('logout/', Logout.as_view(), name='admin_logout'),
    path('dashboard/', Dashboard.as_view(), name='admin_dashboard'),
    path('disciplines/', DisciplineList.as_view(), name='discipline_list'),
    path('disciplines/create/', DisciplineCreate.as_view(), name='discipline_add'),
    path('disciplines/update/<slug>', DisciplineUpdate.as_view(), name='discipline_update'),
    path('disciplines/delete/<slug>', DisciplineDelete.as_view(), name='discipline_delete'),
    path('sub-disciplines/', SubDisciplineList.as_view(), name='sub_discipline_list'),
    path('sub-disciplines/create/', SubDisciplineCreate.as_view(), name='sub_discipline_add'),
    path('sub-disciplines/update/<slug>', SubDisciplineUpdate.as_view(), name='sub_discipline_update'),
    path('sub-disciplines/delete/<slug>', SubDisciplineDelete.as_view(), name='sub_discipline_delete'),
    path('university/', UniversityList.as_view(), name='university_list'),
    path('university/create/', UniversityCreate.as_view(), name='university_add'),
    path('university/update/<slug>', UniversityUpdate.as_view(), name='university_update'),
    path('university/delete/<slug>', UniversityDelete.as_view(), name='university_delete'),
    path('degree/', DegreeList.as_view(), name='degree_list'),
    path('degree/create/', DegreeCreate.as_view(), name='degree_add'),
    path('degree/update/<slug>', DegreeUpdate.as_view(), name='degree_update'),
    path('degree/delete/<slug>', DegreeDelete.as_view(), name='degree_delete'),
    path('designation/', DesignationList.as_view(), name='designation_list'),
    path('designation/create/', DesignationCreate.as_view(), name='designation_add'),
    path('designation/update/<slug>', DesignationUpdate.as_view(), name='designation_update'),
    path('designation/delete/<slug>', DesignationDelete.as_view(), name='designation_delete'),
    path('degree/retrieve-via-university/', get_university_via_degree, name='retrieve_deg_via_uni'),
    path('brand/', BrandList.as_view(), name='brand_list'),
    path('brand/create/', BrandCreate.as_view(), name='brand_add'),
    path('brand/update/<slug>', BrandUpdate.as_view(), name='brand_update'),
    path('brand/delete/<slug>', BrandDelete.as_view(), name='brand_delete'),
    path('manufacturer/', ManufacturerList.as_view(), name='manufacturer_list'),
    path('manufacturer/create/', ManufacturerCreate.as_view(), name='manufacturer_add'),
    path('manufacturer/update/<slug>', ManufacturerUpdate.as_view(), name='manufacturer_update'),
    path('manufacturer/delete/<slug>', ManufacturerDelete.as_view(), name='manufacturer_delete'),
    path('groups/', GroupList.as_view(), name='group_list'),
    path('groups/create/', GroupCreate.as_view(), name='group_add'),
    path('groups/<pk>/update/', GroupUpdate.as_view(), name='group_update'),
    path('agents/', AgentList.as_view(), name='agent_list'),
    path('agents/create/', AgentCreate.as_view(), name='agent_add'),
    path('agents/update/<pk>/profile', AgentProfileView.as_view(), name='agent_profile_update'),
    path('agents/change-password/<pk>', AgentChangePassword.as_view(), name='agent_password_change'),
    path('agents/<pk>/warehouse', AgentWarehouse.as_view(), name='agent_warehouse'),
    path('agents/<pk>/warehouse/add', AgentWarehouseCreate.as_view(), name='agent_warehouse_add'),
]
